# Generated by Django 6.1 on 2026-09-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_order', '0002_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
